- name: Copy Logstash Repo
  copy:
    src: logstash.repo
    dest: /etc/yum.repos.d/logstash.repo

- name: Install Java 
  yum:
    name: java 
    state: installed 

- name: Install Logstash 
  yum:
    name: logstash 
    state: installed 

- name: 