- name: Copy Kibana Repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo

- name: Install Kibana 
  package:
    name: kibana 

- name: Start Kibana 
  service:
    name: kibana
    state: started 