- name: Copy Kibana Repo
  copy:
    src: kibana.repo
    dest: /etc/yum.repos.d/kibana.repo

- name: Install Kibana 
  package:
    name: kibana 

- name: Update kibana config 
  blockinfile:
    path: /etc/kibana/kibana.yml
    insertafter: "^#server.port: 5601"
    block: |
      server.port: 5601
      server.host: 0.0.0.0

- name: Start Kibana 
  service:
    name: kibana
    state: started 
